# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\py_code\StepScanMeter\core\QT\ui_instrumentsMonitor.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Ui_InstrumentsMonitor(object):
    def setupUi(self, Ui_InstrumentsMonitor):
        Ui_InstrumentsMonitor.setObjectName("Ui_InstrumentsMonitor")
        Ui_InstrumentsMonitor.resize(275, 638)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_lockin = QtWidgets.QGroupBox(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_lockin.sizePolicy().hasHeightForWidth())
        self.groupBox_lockin.setSizePolicy(sizePolicy)
        self.groupBox_lockin.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_lockin.setFont(font)
        self.groupBox_lockin.setObjectName("groupBox_lockin")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_lockin)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_X = QtWidgets.QLabel(self.groupBox_lockin)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_X.setFont(font)
        self.label_X.setObjectName("label_X")
        self.gridLayout_3.addWidget(self.label_X, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_Y = QtWidgets.QLabel(self.groupBox_lockin)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_Y.setFont(font)
        self.label_Y.setObjectName("label_Y")
        self.gridLayout_3.addWidget(self.label_Y, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.numLabel_X = QtWidgets.QLabel(self.groupBox_lockin)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.numLabel_X.setFont(font)
        self.numLabel_X.setScaledContents(False)
        self.numLabel_X.setObjectName("numLabel_X")
        self.gridLayout_3.addWidget(self.numLabel_X, 0, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.numLabel_Y = QtWidgets.QLabel(self.groupBox_lockin)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.numLabel_Y.setFont(font)
        self.numLabel_Y.setObjectName("numLabel_Y")
        self.gridLayout_3.addWidget(self.numLabel_Y, 1, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.verticalLayout.addWidget(self.groupBox_lockin)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.groupBox_temperatureController = QtWidgets.QGroupBox(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_temperatureController.sizePolicy().hasHeightForWidth())
        self.groupBox_temperatureController.setSizePolicy(sizePolicy)
        self.groupBox_temperatureController.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_temperatureController.setFont(font)
        self.groupBox_temperatureController.setObjectName("groupBox_temperatureController")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_temperatureController)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_setTemperature = QtWidgets.QLabel(self.groupBox_temperatureController)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_setTemperature.setFont(font)
        self.label_setTemperature.setObjectName("label_setTemperature")
        self.gridLayout_5.addWidget(self.label_setTemperature, 0, 0, 1, 1)
        self.label_currentTemperature = QtWidgets.QLabel(self.groupBox_temperatureController)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_currentTemperature.setFont(font)
        self.label_currentTemperature.setObjectName("label_currentTemperature")
        self.gridLayout_5.addWidget(self.label_currentTemperature, 1, 0, 1, 1)
        self.numLabel_currentTemperature = QtWidgets.QLabel(self.groupBox_temperatureController)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.numLabel_currentTemperature.setFont(font)
        self.numLabel_currentTemperature.setObjectName("numLabel_currentTemperature")
        self.gridLayout_5.addWidget(self.numLabel_currentTemperature, 1, 1, 1, 1)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_temperatureController)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.gridLayout_5.addWidget(self.doubleSpinBox, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_temperatureController)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.groupBox_stage = QtWidgets.QGroupBox(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_stage.sizePolicy().hasHeightForWidth())
        self.groupBox_stage.setSizePolicy(sizePolicy)
        self.groupBox_stage.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_stage.setFont(font)
        self.groupBox_stage.setObjectName("groupBox_stage")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_stage)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox_stage)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.button_moveRight = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_moveRight.sizePolicy().hasHeightForWidth())
        self.button_moveRight.setSizePolicy(sizePolicy)
        self.button_moveRight.setObjectName("button_moveRight")
        self.gridLayout_9.addWidget(self.button_moveRight, 0, 2, 2, 1)
        self.button_moveLeft = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_moveLeft.sizePolicy().hasHeightForWidth())
        self.button_moveLeft.setSizePolicy(sizePolicy)
        self.button_moveLeft.setObjectName("button_moveLeft")
        self.gridLayout_9.addWidget(self.button_moveLeft, 0, 0, 2, 1)
        self.stepSizeSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.stepSizeSpinBox.setObjectName("stepSizeSpinBox")
        self.gridLayout_9.addWidget(self.stepSizeSpinBox, 1, 1, 1, 1)
        self.label_step = QtWidgets.QLabel(self.groupBox_2)
        self.label_step.setObjectName("label_step")
        self.gridLayout_9.addWidget(self.label_step, 0, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.gridLayout_6.addWidget(self.groupBox_2, 3, 0, 1, 2)
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_stage)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_6.addWidget(self.pushButton_3, 2, 1, 1, 1)
        self.label_setZeroPosition = QtWidgets.QLabel(self.groupBox_stage)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_setZeroPosition.setFont(font)
        self.label_setZeroPosition.setObjectName("label_setZeroPosition")
        self.gridLayout_6.addWidget(self.label_setZeroPosition, 0, 1, 1, 1)
        self.lockinMonitorLabel_x_3 = QtWidgets.QLabel(self.groupBox_stage)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lockinMonitorLabel_x_3.setFont(font)
        self.lockinMonitorLabel_x_3.setObjectName("lockinMonitorLabel_x_3")
        self.gridLayout_6.addWidget(self.lockinMonitorLabel_x_3, 0, 0, 1, 1)
        self.lockinMonitorLabel_x_4 = QtWidgets.QLabel(self.groupBox_stage)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lockinMonitorLabel_x_4.setFont(font)
        self.lockinMonitorLabel_x_4.setObjectName("lockinMonitorLabel_x_4")
        self.gridLayout_6.addWidget(self.lockinMonitorLabel_x_4, 2, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_stage)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_6.addWidget(self.label_6, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.spin_setTimeZero = QtWidgets.QDoubleSpinBox(self.groupBox_stage)
        self.spin_setTimeZero.setObjectName("spin_setTimeZero")
        self.gridLayout_6.addWidget(self.spin_setTimeZero, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_stage)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        Ui_InstrumentsMonitor.setWidget(self.dockWidgetContents)

        self.retranslateUi(Ui_InstrumentsMonitor)
        QtCore.QMetaObject.connectSlotsByName(Ui_InstrumentsMonitor)

    def retranslateUi(self, Ui_InstrumentsMonitor):
        _translate = QtCore.QCoreApplication.translate
        Ui_InstrumentsMonitor.setWindowTitle(_translate("Ui_InstrumentsMonitor", "Instruments Monitor"))
        self.groupBox_lockin.setTitle(_translate("Ui_InstrumentsMonitor", "Lock-in"))
        self.label_X.setText(_translate("Ui_InstrumentsMonitor", "X"))
        self.label_Y.setText(_translate("Ui_InstrumentsMonitor", "Y"))
        self.numLabel_X.setText(_translate("Ui_InstrumentsMonitor", "0.0"))
        self.numLabel_Y.setText(_translate("Ui_InstrumentsMonitor", "0.0"))
        self.groupBox_temperatureController.setTitle(_translate("Ui_InstrumentsMonitor", "Temperature Controller"))
        self.label_setTemperature.setText(_translate("Ui_InstrumentsMonitor", "Set temperature"))
        self.label_currentTemperature.setText(_translate("Ui_InstrumentsMonitor", "Current Temp."))
        self.numLabel_currentTemperature.setText(_translate("Ui_InstrumentsMonitor", "0.0"))
        self.groupBox_stage.setTitle(_translate("Ui_InstrumentsMonitor", "Stage"))
        self.groupBox_2.setTitle(_translate("Ui_InstrumentsMonitor", "Controls"))
        self.button_moveRight.setText(_translate("Ui_InstrumentsMonitor", ">"))
        self.button_moveLeft.setText(_translate("Ui_InstrumentsMonitor", "<"))
        self.label_step.setText(_translate("Ui_InstrumentsMonitor", "step"))
        self.pushButton_3.setText(_translate("Ui_InstrumentsMonitor", "Set new Zero"))
        self.label_setZeroPosition.setText(_translate("Ui_InstrumentsMonitor", "set Zero position"))
        self.lockinMonitorLabel_x_3.setText(_translate("Ui_InstrumentsMonitor", "Current Position"))
        self.lockinMonitorLabel_x_4.setText(_translate("Ui_InstrumentsMonitor", "Move Stage"))
        self.label_6.setText(_translate("Ui_InstrumentsMonitor", "0.0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Ui_InstrumentsMonitor = QtWidgets.QDockWidget()
    ui = Ui_Ui_InstrumentsMonitor()
    ui.setupUi(Ui_InstrumentsMonitor)
    Ui_InstrumentsMonitor.show()
    sys.exit(app.exec_())

