# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\py_code\StepScanMeter\measurement\QT\ui_setupTimescale.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Ui_SetupTimeScale(object):
    def setupUi(self, Ui_SetupTimeScale):
        Ui_SetupTimeScale.setObjectName("Ui_SetupTimeScale")
        Ui_SetupTimeScale.resize(224, 263)
        Ui_SetupTimeScale.setAutoFillBackground(False)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.dockWidgetContents)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_From = QtWidgets.QLabel(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_From.sizePolicy().hasHeightForWidth())
        self.label_From.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_From.setFont(font)
        self.label_From.setObjectName("label_From")
        self.gridLayout_2.addWidget(self.label_From, 0, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_Step = QtWidgets.QLabel(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Step.sizePolicy().hasHeightForWidth())
        self.label_Step.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_Step.setFont(font)
        self.label_Step.setObjectName("label_Step")
        self.gridLayout_2.addWidget(self.label_Step, 0, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_use = QtWidgets.QLabel(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_use.sizePolicy().hasHeightForWidth())
        self.label_use.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_use.setFont(font)
        self.label_use.setObjectName("label_use")
        self.gridLayout_2.addWidget(self.label_use, 0, 0, 1, 1)
        self.checkBox_use0 = QtWidgets.QCheckBox(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_use0.sizePolicy().hasHeightForWidth())
        self.checkBox_use0.setSizePolicy(sizePolicy)
        self.checkBox_use0.setText("")
        self.checkBox_use0.setChecked(True)
        self.checkBox_use0.setObjectName("checkBox_use0")
        self.gridLayout_2.addWidget(self.checkBox_use0, 1, 0, 1, 1)
        self.spin_timescale_from_2 = QtWidgets.QDoubleSpinBox(self.dockWidgetContents)
        self.spin_timescale_from_2.setSuffix("")
        self.spin_timescale_from_2.setObjectName("spin_timescale_from_2")
        self.gridLayout_2.addWidget(self.spin_timescale_from_2, 2, 1, 1, 1)
        self.spin_timescale_from_1 = QtWidgets.QDoubleSpinBox(self.dockWidgetContents)
        self.spin_timescale_from_1.setSuffix("")
        self.spin_timescale_from_1.setMinimum(-1000.0)
        self.spin_timescale_from_1.setMaximum(1000.0)
        self.spin_timescale_from_1.setObjectName("spin_timescale_from_1")
        self.gridLayout_2.addWidget(self.spin_timescale_from_1, 1, 1, 1, 1)
        self.spin_timescale_step_1 = QtWidgets.QDoubleSpinBox(self.dockWidgetContents)
        self.spin_timescale_step_1.setSuffix("")
        self.spin_timescale_step_1.setObjectName("spin_timescale_step_1")
        self.gridLayout_2.addWidget(self.spin_timescale_step_1, 1, 2, 1, 1)
        self.checkBox_usemm = QtWidgets.QCheckBox(self.dockWidgetContents)
        self.checkBox_usemm.setObjectName("checkBox_usemm")
        self.gridLayout_2.addWidget(self.checkBox_usemm, 6, 1, 1, 2)
        self.spin_timescale_step_2 = QtWidgets.QDoubleSpinBox(self.dockWidgetContents)
        self.spin_timescale_step_2.setSuffix("")
        self.spin_timescale_step_2.setObjectName("spin_timescale_step_2")
        self.gridLayout_2.addWidget(self.spin_timescale_step_2, 2, 2, 1, 1)
        self.checkBox_use1 = QtWidgets.QCheckBox(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_use1.sizePolicy().hasHeightForWidth())
        self.checkBox_use1.setSizePolicy(sizePolicy)
        self.checkBox_use1.setText("")
        self.checkBox_use1.setChecked(True)
        self.checkBox_use1.setObjectName("checkBox_use1")
        self.gridLayout_2.addWidget(self.checkBox_use1, 2, 0, 1, 1)
        self.spin_timescale_step_4 = QtWidgets.QDoubleSpinBox(self.dockWidgetContents)
        self.spin_timescale_step_4.setObjectName("spin_timescale_step_4")
        self.gridLayout_2.addWidget(self.spin_timescale_step_4, 4, 2, 1, 1)
        self.checkBox_use2 = QtWidgets.QCheckBox(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_use2.sizePolicy().hasHeightForWidth())
        self.checkBox_use2.setSizePolicy(sizePolicy)
        self.checkBox_use2.setText("")
        self.checkBox_use2.setChecked(True)
        self.checkBox_use2.setObjectName("checkBox_use2")
        self.gridLayout_2.addWidget(self.checkBox_use2, 3, 0, 1, 1)
        self.spin_timescale_step_3 = QtWidgets.QDoubleSpinBox(self.dockWidgetContents)
        self.spin_timescale_step_3.setSuffix("")
        self.spin_timescale_step_3.setObjectName("spin_timescale_step_3")
        self.gridLayout_2.addWidget(self.spin_timescale_step_3, 3, 2, 1, 1)
        self.vtimescale_from_5 = QtWidgets.QDoubleSpinBox(self.dockWidgetContents)
        self.vtimescale_from_5.setObjectName("vtimescale_from_5")
        self.gridLayout_2.addWidget(self.vtimescale_from_5, 5, 1, 1, 1)
        self.spin_timescale_from_4 = QtWidgets.QDoubleSpinBox(self.dockWidgetContents)
        self.spin_timescale_from_4.setObjectName("spin_timescale_from_4")
        self.gridLayout_2.addWidget(self.spin_timescale_from_4, 4, 1, 1, 1)
        self.checkBox_use4 = QtWidgets.QCheckBox(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_use4.sizePolicy().hasHeightForWidth())
        self.checkBox_use4.setSizePolicy(sizePolicy)
        self.checkBox_use4.setText("")
        self.checkBox_use4.setObjectName("checkBox_use4")
        self.gridLayout_2.addWidget(self.checkBox_use4, 5, 0, 1, 1)
        self.spin_timescale_from_3 = QtWidgets.QDoubleSpinBox(self.dockWidgetContents)
        self.spin_timescale_from_3.setSuffix("")
        self.spin_timescale_from_3.setObjectName("spin_timescale_from_3")
        self.gridLayout_2.addWidget(self.spin_timescale_from_3, 3, 1, 1, 1)
        self.checkBox_use3 = QtWidgets.QCheckBox(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_use3.sizePolicy().hasHeightForWidth())
        self.checkBox_use3.setSizePolicy(sizePolicy)
        self.checkBox_use3.setText("")
        self.checkBox_use3.setObjectName("checkBox_use3")
        self.gridLayout_2.addWidget(self.checkBox_use3, 4, 0, 1, 1)
        self.button_apply = QtWidgets.QPushButton(self.dockWidgetContents)
        self.button_apply.setObjectName("button_apply")
        self.gridLayout_2.addWidget(self.button_apply, 5, 2, 1, 1)
        Ui_SetupTimeScale.setWidget(self.dockWidgetContents)

        self.retranslateUi(Ui_SetupTimeScale)
        QtCore.QMetaObject.connectSlotsByName(Ui_SetupTimeScale)

    def retranslateUi(self, Ui_SetupTimeScale):
        _translate = QtCore.QCoreApplication.translate
        Ui_SetupTimeScale.setWindowTitle(_translate("Ui_SetupTimeScale", "Stage Setup"))
        self.label_From.setText(_translate("Ui_SetupTimeScale", "from (ps)"))
        self.label_Step.setText(_translate("Ui_SetupTimeScale", "step (ps)"))
        self.label_use.setText(_translate("Ui_SetupTimeScale", "use"))
        self.checkBox_usemm.setText(_translate("Ui_SetupTimeScale", "Use scale in mm"))
        self.button_apply.setText(_translate("Ui_SetupTimeScale", "Apply"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Ui_SetupTimeScale = QtWidgets.QDockWidget()
    ui = Ui_Ui_SetupTimeScale()
    ui.setupUi(Ui_SetupTimeScale)
    Ui_SetupTimeScale.show()
    sys.exit(app.exec_())

