# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\py_code\StepScanMeter\measurement\QT\ui_scanMonitor.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_UI_ScanMonitor(object):
    def setupUi(self, UI_ScanMonitor):
        UI_ScanMonitor.setObjectName("UI_ScanMonitor")
        UI_ScanMonitor.resize(1399, 263)
        UI_ScanMonitor.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.dockWidgetContents)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.box_currentScanStatus = QtWidgets.QGroupBox(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.box_currentScanStatus.setFont(font)
        self.box_currentScanStatus.setObjectName("box_currentScanStatus")
        self.gridLayout = QtWidgets.QGridLayout(self.box_currentScanStatus)
        self.gridLayout.setObjectName("gridLayout")
        self.numLabel_currentTimeLeft = QtWidgets.QLabel(self.box_currentScanStatus)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.numLabel_currentTimeLeft.setFont(font)
        self.numLabel_currentTimeLeft.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.numLabel_currentTimeLeft.setObjectName("numLabel_currentTimeLeft")
        self.gridLayout.addWidget(self.numLabel_currentTimeLeft, 1, 1, 1, 1)
        self.numLabel_currentTime = QtWidgets.QLabel(self.box_currentScanStatus)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.numLabel_currentTime.setFont(font)
        self.numLabel_currentTime.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.numLabel_currentTime.setObjectName("numLabel_currentTime")
        self.gridLayout.addWidget(self.numLabel_currentTime, 1, 2, 1, 1)
        self.label_time = QtWidgets.QLabel(self.box_currentScanStatus)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_time.setFont(font)
        self.label_time.setTextFormat(QtCore.Qt.AutoText)
        self.label_time.setObjectName("label_time")
        self.gridLayout.addWidget(self.label_time, 1, 0, 1, 1)
        self.numLabel_currentTotalPoints = QtWidgets.QLabel(self.box_currentScanStatus)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.numLabel_currentTotalPoints.setFont(font)
        self.numLabel_currentTotalPoints.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.numLabel_currentTotalPoints.setObjectName("numLabel_currentTotalPoints")
        self.gridLayout.addWidget(self.numLabel_currentTotalPoints, 0, 2, 1, 1)
        self.label_currentPoint = QtWidgets.QLabel(self.box_currentScanStatus)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_currentPoint.setFont(font)
        self.label_currentPoint.setTextFormat(QtCore.Qt.AutoText)
        self.label_currentPoint.setObjectName("label_currentPoint")
        self.gridLayout.addWidget(self.label_currentPoint, 0, 0, 1, 1)
        self.numLabel_currentPoint = QtWidgets.QLabel(self.box_currentScanStatus)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.numLabel_currentPoint.setFont(font)
        self.numLabel_currentPoint.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.numLabel_currentPoint.setObjectName("numLabel_currentPoint")
        self.gridLayout.addWidget(self.numLabel_currentPoint, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 3, 1, 1)
        self.progressBar_currentScan = QtWidgets.QProgressBar(self.box_currentScanStatus)
        self.progressBar_currentScan.setMinimumSize(QtCore.QSize(0, 10))
        self.progressBar_currentScan.setProperty("value", 0)
        self.progressBar_currentScan.setTextVisible(True)
        self.progressBar_currentScan.setObjectName("progressBar_currentScan")
        self.gridLayout.addWidget(self.progressBar_currentScan, 2, 0, 1, 4)
        self.gridLayout_3.addWidget(self.box_currentScanStatus, 1, 2, 1, 1)
        self.box_totalScanStatus = QtWidgets.QGroupBox(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.box_totalScanStatus.setFont(font)
        self.box_totalScanStatus.setObjectName("box_totalScanStatus")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.box_totalScanStatus)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_completitionTime = QtWidgets.QLabel(self.box_totalScanStatus)
        self.label_completitionTime.setObjectName("label_completitionTime")
        self.gridLayout_2.addWidget(self.label_completitionTime, 0, 7, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 5, 1, 1)
        self.label_endsat = QtWidgets.QLabel(self.box_totalScanStatus)
        self.label_endsat.setObjectName("label_endsat")
        self.gridLayout_2.addWidget(self.label_endsat, 0, 6, 1, 1)
        self.label_time_2 = QtWidgets.QLabel(self.box_totalScanStatus)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_time_2.setFont(font)
        self.label_time_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_time_2.setObjectName("label_time_2")
        self.gridLayout_2.addWidget(self.label_time_2, 0, 1, 1, 1)
        self.numLabel_totalTimeLeft = QtWidgets.QLabel(self.box_totalScanStatus)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.numLabel_totalTimeLeft.setFont(font)
        self.numLabel_totalTimeLeft.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.numLabel_totalTimeLeft.setObjectName("numLabel_totalTimeLeft")
        self.gridLayout_2.addWidget(self.numLabel_totalTimeLeft, 0, 2, 1, 1)
        self.numLabel_totalTime = QtWidgets.QLabel(self.box_totalScanStatus)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.numLabel_totalTime.setFont(font)
        self.numLabel_totalTime.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.numLabel_totalTime.setObjectName("numLabel_totalTime")
        self.gridLayout_2.addWidget(self.numLabel_totalTime, 0, 4, 1, 1)
        self.progressBar_totalScans = QtWidgets.QProgressBar(self.box_totalScanStatus)
        self.progressBar_totalScans.setMinimumSize(QtCore.QSize(0, 10))
        self.progressBar_totalScans.setProperty("value", 0)
        self.progressBar_totalScans.setTextVisible(True)
        self.progressBar_totalScans.setObjectName("progressBar_totalScans")
        self.gridLayout_2.addWidget(self.progressBar_totalScans, 2, 0, 1, 8)
        self.gridLayout_3.addWidget(self.box_totalScanStatus, 2, 2, 1, 1)
        self.lineEdit_scanName = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.lineEdit_scanName.setObjectName("lineEdit_scanName")
        self.gridLayout_3.addWidget(self.lineEdit_scanName, 0, 2, 1, 1)
        self.label_name = QtWidgets.QLabel(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_name.setFont(font)
        self.label_name.setTextFormat(QtCore.Qt.AutoText)
        self.label_name.setObjectName("label_name")
        self.gridLayout_3.addWidget(self.label_name, 0, 0, 1, 1)
        self.box_scanSettings = QtWidgets.QGroupBox(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.box_scanSettings.sizePolicy().hasHeightForWidth())
        self.box_scanSettings.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.box_scanSettings.setFont(font)
        self.box_scanSettings.setObjectName("box_scanSettings")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.box_scanSettings)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.spinBox_averages = QtWidgets.QSpinBox(self.box_scanSettings)
        self.spinBox_averages.setObjectName("spinBox_averages")
        self.gridLayout_11.addWidget(self.spinBox_averages, 1, 1, 1, 1)
        self.label_averages = QtWidgets.QLabel(self.box_scanSettings)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_averages.setFont(font)
        self.label_averages.setTextFormat(QtCore.Qt.AutoText)
        self.label_averages.setObjectName("label_averages")
        self.gridLayout_11.addWidget(self.label_averages, 1, 0, 1, 1)
        self.button_stopScan = QtWidgets.QPushButton(self.box_scanSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_stopScan.sizePolicy().hasHeightForWidth())
        self.button_stopScan.setSizePolicy(sizePolicy)
        self.button_stopScan.setObjectName("button_stopScan")
        self.gridLayout_11.addWidget(self.button_stopScan, 3, 1, 1, 1)
        self.button_startScan = QtWidgets.QPushButton(self.box_scanSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_startScan.sizePolicy().hasHeightForWidth())
        self.button_startScan.setSizePolicy(sizePolicy)
        self.button_startScan.setObjectName("button_startScan")
        self.gridLayout_11.addWidget(self.button_startScan, 3, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem2, 4, 0, 1, 1)
        self.gridLayout_3.addWidget(self.box_scanSettings, 1, 0, 2, 1)
        UI_ScanMonitor.setWidget(self.dockWidgetContents)

        self.retranslateUi(UI_ScanMonitor)
        QtCore.QMetaObject.connectSlotsByName(UI_ScanMonitor)

    def retranslateUi(self, UI_ScanMonitor):
        _translate = QtCore.QCoreApplication.translate
        UI_ScanMonitor.setWindowTitle(_translate("UI_ScanMonitor", "Scan Monitor"))
        self.box_currentScanStatus.setTitle(_translate("UI_ScanMonitor", "Current Scan Status"))
        self.numLabel_currentTimeLeft.setText(_translate("UI_ScanMonitor", "0.0"))
        self.numLabel_currentTime.setText(_translate("UI_ScanMonitor", "0.0"))
        self.label_time.setText(_translate("UI_ScanMonitor", "Time"))
        self.numLabel_currentTotalPoints.setText(_translate("UI_ScanMonitor", "0.0"))
        self.label_currentPoint.setText(_translate("UI_ScanMonitor", "Current Point"))
        self.numLabel_currentPoint.setText(_translate("UI_ScanMonitor", "0.0"))
        self.box_totalScanStatus.setTitle(_translate("UI_ScanMonitor", "Total Scan Status"))
        self.label_completitionTime.setText(_translate("UI_ScanMonitor", "12:12"))
        self.label_endsat.setText(_translate("UI_ScanMonitor", "ends at:"))
        self.label_time_2.setText(_translate("UI_ScanMonitor", "Time           "))
        self.numLabel_totalTimeLeft.setText(_translate("UI_ScanMonitor", "0.0"))
        self.numLabel_totalTime.setText(_translate("UI_ScanMonitor", "0.0"))
        self.label_name.setText(_translate("UI_ScanMonitor", "Scan Name:"))
        self.box_scanSettings.setTitle(_translate("UI_ScanMonitor", "Settings"))
        self.label_averages.setText(_translate("UI_ScanMonitor", "Number of Averages"))
        self.button_stopScan.setText(_translate("UI_ScanMonitor", "Stop after Current"))
        self.button_startScan.setText(_translate("UI_ScanMonitor", "Start StepScan"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    UI_ScanMonitor = QtWidgets.QDockWidget()
    ui = Ui_UI_ScanMonitor()
    ui.setupUi(UI_ScanMonitor)
    UI_ScanMonitor.show()
    sys.exit(app.exec_())

