# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\lib\StepScan_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1337, 864)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(1280, 600))
        self.centralwidget.setMaximumSize(QtCore.QSize(1920, 1080))
        self.centralwidget.setBaseSize(QtCore.QSize(0, 0))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1318, 813))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gb_parameters = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gb_parameters.sizePolicy().hasHeightForWidth())
        self.gb_parameters.setSizePolicy(sizePolicy)
        self.gb_parameters.setObjectName("gb_parameters")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.gb_parameters)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tree_parameters = QtWidgets.QTreeWidget(self.gb_parameters)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tree_parameters.sizePolicy().hasHeightForWidth())
        self.tree_parameters.setSizePolicy(sizePolicy)
        self.tree_parameters.setMinimumSize(QtCore.QSize(200, 0))
        self.tree_parameters.setObjectName("tree_parameters")
        self.tree_parameters.headerItem().setText(0, "1")
        self.verticalLayout_5.addWidget(self.tree_parameters)
        self.label_notes = QtWidgets.QLabel(self.gb_parameters)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_notes.setFont(font)
        self.label_notes.setObjectName("label_notes")
        self.verticalLayout_5.addWidget(self.label_notes)
        self.textbox_notes = QtWidgets.QTextBrowser(self.gb_parameters)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textbox_notes.sizePolicy().hasHeightForWidth())
        self.textbox_notes.setSizePolicy(sizePolicy)
        self.textbox_notes.setObjectName("textbox_notes")
        self.verticalLayout_5.addWidget(self.textbox_notes)
        self.horizontalLayout.addWidget(self.gb_parameters)
        self.tabWidget_plots = QtWidgets.QTabWidget(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget_plots.sizePolicy().hasHeightForWidth())
        self.tabWidget_plots.setSizePolicy(sizePolicy)
        self.tabWidget_plots.setMinimumSize(QtCore.QSize(805, 605))
        self.tabWidget_plots.setObjectName("tabWidget_plots")
        self.tab_currentScan = QtWidgets.QWidget()
        self.tab_currentScan.setObjectName("tab_currentScan")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_currentScan)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.plot_currentScan = PlotWidget(self.tab_currentScan)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot_currentScan.sizePolicy().hasHeightForWidth())
        self.plot_currentScan.setSizePolicy(sizePolicy)
        self.plot_currentScan.setMinimumSize(QtCore.QSize(800, 600))
        self.plot_currentScan.setObjectName("plot_currentScan")
        self.verticalLayout_4.addWidget(self.plot_currentScan)
        self.progressBar = QtWidgets.QProgressBar(self.tab_currentScan)
        self.progressBar.setMinimumSize(QtCore.QSize(0, 10))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_4.addWidget(self.progressBar)
        self.gb_title = QtWidgets.QGroupBox(self.tab_currentScan)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gb_title.sizePolicy().hasHeightForWidth())
        self.gb_title.setSizePolicy(sizePolicy)
        self.gb_title.setMinimumSize(QtCore.QSize(0, 0))
        self.gb_title.setObjectName("gb_title")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gb_title)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_11 = QtWidgets.QLabel(self.gb_title)
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gb_title)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 0, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gb_title)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 0, 4, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gb_title)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 0, 5, 1, 1)
        self.label = QtWidgets.QLabel(self.gb_title)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 1, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gb_title)
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 1, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gb_title)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 1, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gb_title)
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 1, 3, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gb_title)
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 1, 4, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.gb_title)
        self.label_14.setObjectName("label_14")
        self.gridLayout_4.addWidget(self.label_14, 1, 5, 1, 1)
        self.verticalLayout_4.addWidget(self.gb_title)
        self.plot_currentScan.raise_()
        self.gb_title.raise_()
        self.progressBar.raise_()
        self.tabWidget_plots.addTab(self.tab_currentScan, "")
        self.tab_allScans = QtWidgets.QWidget()
        self.tab_allScans.setObjectName("tab_allScans")
        self.plot_allScans = PlotWidget(self.tab_allScans)
        self.plot_allScans.setGeometry(QtCore.QRect(0, 0, 800, 600))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot_allScans.sizePolicy().hasHeightForWidth())
        self.plot_allScans.setSizePolicy(sizePolicy)
        self.plot_allScans.setMinimumSize(QtCore.QSize(800, 600))
        self.plot_allScans.setObjectName("plot_allScans")
        self.tabWidget_plots.addTab(self.tab_allScans, "")
        self.horizontalLayout.addWidget(self.tabWidget_plots)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lockinMonitorLabel_x = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lockinMonitorLabel_x.setFont(font)
        self.lockinMonitorLabel_x.setObjectName("lockinMonitorLabel_x")
        self.verticalLayout_3.addWidget(self.lockinMonitorLabel_x, 0, QtCore.Qt.AlignHCenter)
        self.LockinMonitorLCD_x = QtWidgets.QLCDNumber(self.groupBox_3)
        self.LockinMonitorLCD_x.setObjectName("LockinMonitorLCD_x")
        self.verticalLayout_3.addWidget(self.LockinMonitorLCD_x)
        self.LockinMonitorLabel_y = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.LockinMonitorLabel_y.setFont(font)
        self.LockinMonitorLabel_y.setObjectName("LockinMonitorLabel_y")
        self.verticalLayout_3.addWidget(self.LockinMonitorLabel_y, 0, QtCore.Qt.AlignHCenter)
        self.LockinMonitorLCD_y = QtWidgets.QLCDNumber(self.groupBox_3)
        self.LockinMonitorLCD_y.setObjectName("LockinMonitorLCD_y")
        self.verticalLayout_3.addWidget(self.LockinMonitorLCD_y)
        self.TemperatureMoitorLabel = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.TemperatureMoitorLabel.setFont(font)
        self.TemperatureMoitorLabel.setObjectName("TemperatureMoitorLabel")
        self.verticalLayout_3.addWidget(self.TemperatureMoitorLabel, 0, QtCore.Qt.AlignHCenter)
        self.temperatureMonitorLDC = QtWidgets.QLCDNumber(self.groupBox_3)
        self.temperatureMonitorLDC.setObjectName("temperatureMonitorLDC")
        self.verticalLayout_3.addWidget(self.temperatureMonitorLDC)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.groupBox = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.timescale_step_1 = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.timescale_step_1.setObjectName("timescale_step_1")
        self.gridLayout.addWidget(self.timescale_step_1, 2, 1, 1, 1)
        self.label_timescaleFrom = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_timescaleFrom.sizePolicy().hasHeightForWidth())
        self.label_timescaleFrom.setSizePolicy(sizePolicy)
        self.label_timescaleFrom.setObjectName("label_timescaleFrom")
        self.gridLayout.addWidget(self.label_timescaleFrom, 1, 0, 1, 1)
        self.timescale_from_2 = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.timescale_from_2.setObjectName("timescale_from_2")
        self.gridLayout.addWidget(self.timescale_from_2, 3, 0, 1, 1)
        self.label_timescaleStep = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_timescaleStep.sizePolicy().hasHeightForWidth())
        self.label_timescaleStep.setSizePolicy(sizePolicy)
        self.label_timescaleStep.setObjectName("label_timescaleStep")
        self.gridLayout.addWidget(self.label_timescaleStep, 1, 1, 1, 1)
        self.timescale_from_1 = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.timescale_from_1.setMinimum(-1000.0)
        self.timescale_from_1.setMaximum(1000.0)
        self.timescale_from_1.setObjectName("timescale_from_1")
        self.gridLayout.addWidget(self.timescale_from_1, 2, 0, 1, 1)
        self.timescale_step_2 = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.timescale_step_2.setObjectName("timescale_step_2")
        self.gridLayout.addWidget(self.timescale_step_2, 3, 1, 1, 1)
        self.timescale_step_3 = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.timescale_step_3.setObjectName("timescale_step_3")
        self.gridLayout.addWidget(self.timescale_step_3, 4, 1, 1, 1)
        self.timescale_from_3 = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.timescale_from_3.setObjectName("timescale_from_3")
        self.gridLayout.addWidget(self.timescale_from_3, 4, 0, 1, 1)
        self.timescale_from_4 = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.timescale_from_4.setObjectName("timescale_from_4")
        self.gridLayout.addWidget(self.timescale_from_4, 5, 0, 1, 1)
        self.timescale_step_5 = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.timescale_step_5.setObjectName("timescale_step_5")
        self.gridLayout.addWidget(self.timescale_step_5, 6, 1, 1, 1)
        self.timescale_from_5 = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.timescale_from_5.setObjectName("timescale_from_5")
        self.gridLayout.addWidget(self.timescale_from_5, 6, 0, 1, 1)
        self.timescale_step_4 = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.timescale_step_4.setObjectName("timescale_step_4")
        self.gridLayout.addWidget(self.timescale_step_4, 5, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 7, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.gb_timeAxis = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gb_timeAxis.sizePolicy().hasHeightForWidth())
        self.gb_timeAxis.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.gb_timeAxis.setFont(font)
        self.gb_timeAxis.setObjectName("gb_timeAxis")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gb_timeAxis)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_totalPoints = QtWidgets.QLabel(self.gb_timeAxis)
        self.label_totalPoints.setObjectName("label_totalPoints")
        self.gridLayout_2.addWidget(self.label_totalPoints, 0, 0, 1, 1)
        self.label_totalPoints_number = QtWidgets.QLabel(self.gb_timeAxis)
        self.label_totalPoints_number.setObjectName("label_totalPoints_number")
        self.gridLayout_2.addWidget(self.label_totalPoints_number, 0, 1, 1, 1)
        self.label_timeSpan = QtWidgets.QLabel(self.gb_timeAxis)
        self.label_timeSpan.setObjectName("label_timeSpan")
        self.gridLayout_2.addWidget(self.label_timeSpan, 1, 0, 1, 1)
        self.label_timeSpan_number = QtWidgets.QLabel(self.gb_timeAxis)
        self.label_timeSpan_number.setObjectName("label_timeSpan_number")
        self.gridLayout_2.addWidget(self.label_timeSpan_number, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.gb_timeAxis)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayoutWidget.raise_()
        self.progressBar.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1337, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget_plots.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.gb_parameters.setTitle(_translate("MainWindow", "Parameters"))
        self.label_notes.setText(_translate("MainWindow", "Notes:"))
        self.gb_title.setTitle(_translate("MainWindow", "GroupBox"))
        self.label_11.setText(_translate("MainWindow", "current"))
        self.label_7.setText(_translate("MainWindow", "total"))
        self.label_9.setText(_translate("MainWindow", "Remaining"))
        self.label_6.setText(_translate("MainWindow", "Total"))
        self.label.setText(_translate("MainWindow", "Scan:"))
        self.label_10.setText(_translate("MainWindow", "000"))
        self.label_8.setText(_translate("MainWindow", "000"))
        self.label_13.setText(_translate("MainWindow", "Time"))
        self.label_12.setText(_translate("MainWindow", "000"))
        self.label_14.setText(_translate("MainWindow", "000"))
        self.tabWidget_plots.setTabText(self.tabWidget_plots.indexOf(self.tab_currentScan), _translate("MainWindow", "Tab 1"))
        self.tabWidget_plots.setTabText(self.tabWidget_plots.indexOf(self.tab_allScans), _translate("MainWindow", "Tab 2"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Data Monitor"))
        self.lockinMonitorLabel_x.setText(_translate("MainWindow", "x"))
        self.LockinMonitorLabel_y.setText(_translate("MainWindow", "y"))
        self.TemperatureMoitorLabel.setText(_translate("MainWindow", "Temperature"))
        self.groupBox.setTitle(_translate("MainWindow", "Setup Timescale"))
        self.label_timescaleFrom.setText(_translate("MainWindow", "from"))
        self.label_timescaleStep.setText(_translate("MainWindow", "step"))
        self.pushButton.setText(_translate("MainWindow", "Apply"))
        self.gb_timeAxis.setTitle(_translate("MainWindow", "Time Axis"))
        self.label_totalPoints.setText(_translate("MainWindow", "Total Points:"))
        self.label_totalPoints_number.setText(_translate("MainWindow", "000"))
        self.label_timeSpan.setText(_translate("MainWindow", "Time Span:"))
        self.label_timeSpan_number.setText(_translate("MainWindow", "TextLabel"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))

from pyqtgraph import PlotWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

